version: '3.7'

services:
  native-web:
    image: spring-graalvm-experiment:1-SNAPSHOT
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/demo
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"